name: leanix_task
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  pagination_view: ^2.0.0-nullsafety.0
  cached_network_image: ^2.3.2+1

  # Network
  graphql_flutter: ^3.1.0
  data_connection_checker: ^0.3.4

  # Dart data class
  json_serializable: ^3.5.1
  freezed_annotation: ^0.12.0

  # Dependency Injection
  get_it: ^5.0.6
  injectable: ^1.0.4

  # State management
  flutter_bloc: ^7.0.0

  # Caching
  hive: ^1.4.4+1

  # Misc
  dartz: ^0.9.2
  rxdart: ^0.24.1
  path_provider: ^1.6.27
  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generators
  freezed: ^0.12.1
  injectable_generator: ^1.0.4
  build_runner: ^1.10.1

  # Linting
  effective_dart: ^1.3.0

  # Testing
  bloc_test: ^8.0.0
  mockito: ^4.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
